### ISSUE TITLE
Which of the Forks is the Successor?

### ISSUE THREAD

**Issue by u2n** [andrew867/timeclock#45]
Thx andrew867 for taking up this project. But with development here halted for some time, is there a particular fork (of the 46 at this writing) that can be named as the 'official successor'?

Notable is BoatrightTBC's (https://github.com/BoatrightTBC/timeclock) with 18 further commits. Starting with that version myself since it beats going through each fork one-by-one.

**Comment by Kayoti** [comment]
> Thx andrew867 for taking up this project. But with development here halted for some time, is there a particular fork (of the 46 at this writing) that can be named as the 'official successor'?
> 
> Notable is BoatrightTBC's (https://github.com/BoatrightTBC/timeclock) with 18 further commits. Starting with that version myself since it beats going through each fork one-by-one.

I made an upgrade to the code to work on PHP7 (you can see my pull request) which would be the most recent workable project you can give it a try and see if it is something you can work with 
https://github.com/Kayoti/timeclock
if the project is dead then i will branch off to work on mine as a successor

**Comment by u2n** [comment]
Thanks, @Kayoti, got the email alert and came here to advise "just look at the pull requests," but then noticed I was the one who asked the question lol. Can't believe that was over two years ago.

Curious whether yours incorporates the functional improvements of @BoatrightTBC?

Hoping to find time to work on this before 1/21. Commercial programs bleed funds so can't believe this project doesn't get more attention.

**Comment by Kayoti** [comment]
When i started working on this i was unaware that BoatrightTBC's had some fixes done so most of my fixes are the same but with different style and I did not change the weather plugin the way he did, I was more concern with the fact that the project should work as is. I have more plans for the project in the future looking to give the interface a facelift and perhaps i could resolve some more issues that are open on andrews project

**Comment by BoatrightTBC** [comment]
glad to know someone else is pursuing this.  My potential customer demurred, and I didn't go on with projected improvements.  Style doesn't matter a lot. Function does. 

I'ld like to ensure we're in sync tho.  How can we accomplish that?

**Comment by BoatrightTBC** [comment]
Comparing yours and mine, yes, there is a stylistic difference, mostly regarding how I did calls to mysqli vs your cleaner-simpler version (good on you!) but in addition, there are other issues: 

- Your version retains all the old NOAA code for weather in the leftmain.php file including all the logical stuff around line 350 re if ($display_weather == "yes") which needs to be either deleted or modified to support an existing weather service instead of the old NOAA service they discontinued in case a user sets that to yes in the config file. I pulled all that logic into sidebar-metar-display.php along with instruction changes in admin_index_tpl.php
- Also in leftmain (and admittedly another stylistic issue) I far prefer the logic I used begining at around my line 230, your line 408 regarding displaying errors where I build up an $errors variable then dump it all at once where you create explicit tables for each one which is both a formatting, and screen reader nightmare. Tables should be structural, use CSS for display. This runs from your 408 to the end of the file.
- It lacks all the code for barcode clockins, or essentially any clocking system where the person enters an ID rather than selecting their name. This is a huge difference. 
- Your readme needs substantial updating if only to remove references to version 1.04 which this certainly isn't. You probably need to update the changelog files as well. 
- I moved the sql scripts into a folder along with the sql script to  add the barcode info and to change the db version in upgrade_v1.4-v2.0.sql. This, of course, requires changing the version number from 1.4 to 2.0. 
- Another style thing...  I prefer running isset($tzo) once at the top of the file and setting it instead of writing  $secs = $secs + (($to_timestamp + isset($tzo))  over and over and similarly for other variables.  This is most notable in the reports section. 

If you're open to it I can do a detailed merge and do a pull request to your version... and then direct people to that as the "new baseline" unless you're either adverse to the idea or prefer not to take that on. 

Rick

**Comment by Kayoti** [comment]
waw, thanks for your input I greatly appreciate your contribution to the project, I for sure know that most of my fixes are not efficient nor ideal, when I was working on the project I had no clue someone else was digging deep too 🤣 but my goal was simple retain as much of the project code structure as possible and make it work.
My next step was to improve on the actual code blocks but since I was more interested in the interface facelift as a challenge I wanted a stable code to run first. 
I would be extremely happy if the pull can be merged with yours somehow and yes I didn't bother with the readme yet since I wasn't sure what to call my fork yet.

**Comment by Kayoti** [comment]
I would definitely merge and pull which ever is easier towards your project or mine I do want to integrate your changes too for sure

**Comment by u2n** [comment]
Glad to see this back in development. It appears the **@BoatrightTBC [timeclock project](https://github.com/BoatrightTBC/timeclock)** is the successor (since that's where the commits are going). Thanks also @Kayoti, @bonnedav, @duelafn and future contributors.

With that, this issue is closed.
